### PR TITLE
Add ability to install globally and execute as command line app

### PR DESCRIPTION
**Pull request by luisvt**

### CODE REVIEW

**Comment by mprobst** [comment]
Thanks for the contribution!

I think the build failure might be a fluke (pub install something something), rerunning tests now to see if that's true.

**Comment by mprobst** [comment]
I see, I think you might have to just bump the version of "test" in this file to `0.12.15`:
`https://github.com/angular/ts2dart/blob/master/test/e2e/pubspec.yaml`

Sorry for the yak shaving required here, this project has been somewhat less than active for a while, so bit rot creeps in.

**Comment by luisvt** [comment]
Thanks, I will do it

**Comment by mprobst** [comment]
Thanks, merged!

**Comment by mprobst** [comment]
This has been released as `0.9.11`.

**Pull request merged**
