### PR TITLE
Move tsd to a regular dependency

### PR DESCRIPTION
**Pull request by alexeagle**

### CODE REVIEW

**Comment by alexeagle** [comment]
Fixes #128

**Comment by alexeagle** [comment]
(note, I'm surprised that the preinstall script succeeded - I expected it to complain that tsd had not yet been installed. but Travis passes. any idea why?)

**Comment by mprobst** [comment]
LGTM

Wouldn't the preinstall succeed because it explicitly installs tsd?

**Comment by alexeagle** [comment]
Yeah but preinstall before install right?

**Comment by mprobst** [comment]
Yeah but this just called "npm install" in the preinstall, so that's how that worked? At least that'd be my theory.

**Comment by alexeagle** [comment]
@IgorMinar : merged in 5af57c39cfaa46f2f89305310ce5c65628c139a6

**Pull request closed without merging**
