### PR TITLE
chore(build): update to typescript 1.7.3

### PR DESCRIPTION
**Pull request by alexeagle**

### CODE REVIEW

**Comment by alexeagle** [comment]
Angular is waiting on this, and it's trivial (no changes in ts2dart seem needed) so I'll merge.

**Comment by mprobst** [comment]
LGTM. Sorry, I was on a train to New Jersey.

**Comment by mprobst** [comment]
... should we maybe make this a peer dependency?

**Comment by alexeagle** [comment]
Yeah I don't really understand the changes in peer dependencies coming in
NPM 3 but indeed we would like to use the version of typescript brought by
the user rather than our own.

**Pull request merged**
