### PR TITLE
feat(const): Translate CONST_EXPR to const expressions.

### PR DESCRIPTION
**Pull request by mprobst**
This allows to construct compile time literal (const) expressions in Dart, e.g.

```
const bools = CONST_EXPR([true, false, FileNotFound]);
```

### CODE REVIEW

**Comment by mprobst** [comment]
Allows progress on https://github.com/angular/angular/pull/1524.

@tbosch @pkozlowski-opensource FYI.

**Comment by pkozlowski-opensource** [comment]
@mprobst awesome. Shell we have the `CONST_EXPR` defined on the JS/TS side somewhere as well to have one code working correctly for both JS and Dart?

**Comment by mprobst** [comment]
@pkozlowski-opensource yes, the idea is that the TS code would have a global function in `lang.ts`.

Actually let me make sure we'll filter a `CONST_EXPR` import from the Dart output to make this a bit nicer.

**Comment by mprobst** [comment]
This also fixes https://github.com/angular/ts2dart/issues/13 now.

**Comment by tbosch** [comment]
+1!

**Comment by mprobst** [comment]
@alexeagle I'm off for the day, please merge & release if you think this is fine, or take over the change if you think it isn't.

**Comment by alexeagle** [comment]
Looks great, merging now.

**Pull request merged**
