### PR TITLE
fix(Map.forEach): support arrow fn with block body

### PR DESCRIPTION
**Pull request by vicb**

### CODE REVIEW

**Comment by vicb** [comment]
@mprobst or @alexeagle could you please review the PR. It works fine with the linked angular PR.

**Comment by mprobst** [comment]
Taking a look now.

**Comment by mprobst** [comment]
LGTM.

**Comment by vicb** [comment]
thanks Martin, landed as e08b03707d0816747dcb156a5155380a169d62c3

**Pull request closed without merging**
